project:
  type: website

website:
  title: "Peer Kessler, M.A."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - talks.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



